### ISSUE TITLE
Make item title filterable?

### ISSUE THREAD

**Issue by andrejm** [WebDevStudios/cmb2-attached-posts#10]
Not an issue, more of a suggestion. What about making post title filterable when building a list of items for this field? (e.g. https://github.com/WebDevStudios/cmb2-attached-posts/blob/master/cmb2-attached-posts-field.php#L100)

It would allow to enhance the titles with other data such as publish date or meta field values and generally make their presentation more useful.

**Comment by jtsternberg** [comment]
You're right, we should have been using the WordPress api (get_the_title) that way standard filters apply. I updated to do that. To accomplish what you're asking, it's a bit convoluted, but it works: https://gist.github.com/jtsternberg/2dfc3f31e67db8b6b9bb

**Comment by andrejm** [comment]
Did I tell you you are one of my favourite plug-ins?:) Thank you.
