### ISSUE TITLE
Field name arg isn't being used

### ISSUE THREAD

**Issue by zedejose** [WebDevStudios/cmb2-attached-posts#14]
The field name specified in 

`'name'    => 'This should show up';`

isn't being displayed at all, which makes it quickly confusing when you have more than one relationship on the same post (especially if those are relationships of a certain post type with the **same** post type)

**Comment by jtsternberg** [comment]
@zedejose I'm not sure why the label was hidden via css, but I removed that line. If the label isn't desired, simply remove the 'name' attribute on the field config array.

**Comment by zedejose** [comment]
Impeccable service, thank you :)
