### ISSUE TITLE
query posts by order in attached box & support for future posts

### ISSUE THREAD

**Issue by amitrahav** [WebDevStudios/cmb2-attached-posts#15]
hey, 
when i'm querying posts from the attached meta box - it quiers by their menu order and not by their order in the attachment meta box. is there a way doing that not uses foreach?

bonus question:
this is my meta box config: 
```
		$cmb->add_field( array(
			'name'    => pll__( 'מאמרים לדף הבית בעברית', 'cmb2' ),
			'desc'    => pll__( 'יש לגרור את המאמרים או אירועים לטור הימני בכדי שויפיעו בעמוד הבית באתר בעברית.', 'cmb2' ),
			'id'      => $prefix . 'hebrew_posts',
			'type'    => 'custom_attached_posts',
			'options' => array(
				'show_thumbnails' => false, // Show thumbnails on the left
				'filter_boxes'    => true, // Show a text box for filtering the results
				'query_args'      => array( 'posts_per_page' => -1, 'post_type'=>array('post', 'events','page', 'courses'), 'post_status' => array( 'publish','future' )), // override the get_posts args
			)
		) );
```
and yet, it dosent displays future status posts.
does it supported?

**Comment by jtsternberg** [comment]
You can order your query by `post__in`: http://www.codecheese.com/2013/11/get-and-sort-wordpress-posts-by-post-ids-order/

You can have it display future posts by modifying the `query_args` array: https://github.com/WebDevStudios/cmb2-attached-posts/blob/master/example-field-setup.php#L40

**Comment by amitrahav** [comment]
all Works! thanx!
