### ISSUE TITLE
Function to deal with custom post pagination for a custom post type using the ids in the returned array

### ISSUE THREAD

**Issue by monecchi** [WebDevStudios/cmb2-attached-posts#16]
I'd really appreciate if anyone could share a function to deal with post pagination for a custom post type using the ids in the returned array. Thanks for your attention.

**Comment by baikaresandeep** [comment]
Hi @monecchi ,

you can use the [post__in](https://codex.wordpress.org/Class_Reference/WP_Query#Post_.26_Page_Parameters) parameter in WP_Query() and achieve the pagination.

Hope this will help you.

**Comment by monecchi** [comment]
@baikaresandeep Thanks for the input. It really makes sense.

**Comment by anmamtl** [comment]
Hello!
Im trying to achieve this, but Im not sure how to retrieve the IDs attached for the argument. 
Could you point me to the right way?

Thank you :)
