### ISSUE TITLE
storing the attached posts in separate post_meta fields

### ISSUE THREAD

**Issue by cggit** [WebDevStudios/cmb2-attached-posts#17]
Would it feasible to have the option of storing the attached posts as separate entries in post_meta versus the current method of serialized arrays?

This would allow for more efficient many to many relationship queries.

**Comment by jtsternberg** [comment]
It should work to set `'multiple'  => true` in your field config. So to use the example:
```php
	$example_meta->add_field( array(
		'name'     => __( 'Attached Posts', 'cmb2' ),
		'desc'     => __( 'Drag posts from the left column to the right column to attach them to this page.<br />You may rearrange the order of the posts in the right column by dragging and dropping.', 'cmb2' ),
		'id'       => 'attached_cmb2_attached_posts',
		'type'     => 'custom_attached_posts',
		'multiple' => true,
		'options'  => array(
			'show_thumbnails' => true, // Show thumbnails on the left
			'filter_boxes'    => true, // Show a text box for filtering the results
			'query_args'      => array( 'posts_per_page' => 10 ), // override the get_posts args
		)
	) );
```

**Comment by cggit** [comment]
beautiful! Thanks so much. CM2 FTW

Can I ask the reason for using posts_per_page in the example? I don't see any option for pagination so am wondering the implied use case?

**Comment by jtsternberg** [comment]
because it will only show the saved (in your DB) value for posts_per_page. So if you want more than that, you'll have to specify it here, as well as any other get_posts args (like orderby, order, etc).

**Comment by cggit** [comment]
Right. Thanks again.
