### ISSUE TITLE
Loop through attached posts on Blog Page

### ISSUE THREAD

**Issue by elisafern12** [WebDevStudios/cmb2-attached-posts#21]
Hello!
Whenever Im trying to retrieve the attached posts from my blog page, it doesn't work.
It works on single posts or pages, but not the main blog page.

I tried to reset the query and post data after the main loop, I have remove the main blog loop to test too with no avail. Even with a var_dump, there are no values.

Is there something I'm missing?

**My Custom field:**
`function cmb2_attached_posts_field_metaboxes() {

 $prefix = '_cmb_';

```
$example_meta = new_cmb2_box( array(
    'id'           => 'cmb2_attached_posts_field',
    'title'        => __( 'Attached Posts', 'cmb2' ),
    'object_types' => array( 'page' ), // post type
    'show_on'      => array( 'key' => 'id', 'value' => array(925) ),
    'context'      => 'normal',
    'multiple' => true,
    'priority'     => 'high',
    'show_names'   => false, // Show field names on the left
) );
$example_meta->add_field( array(
    'name'    => __( 'Attached Posts', 'cmb2' ),
    'id'      => 'attached_cmb2_attached_posts',
    'type'    => 'custom_attached_posts',
    'options' => array(
        'show_thumbnails' => true,
        'filter_boxes'    => true, 
        'query_args'      => array( 'post' => 20 ),
    )
) );
```

}
add_action( 'cmb2_init', 'cmb2_attached_posts_field_metaboxes' );`
**My Function:**

`function top_posts() {
    $attached = get_post_meta( get_the_ID(), 'attached_cmb2_attached_posts', true ); 
    foreach ( (array) $attached as $key => $attached_post ) {
        var_dump($attached_post);
    echo '<hr>';
        $studentlinks = get_page_link($attached_post);
        echo '<a href="' . $studentlinks . '">';
        echo get_the_title ($attached_post) . '<br>';
    echo '</a>';
}`

Thank you!!

**Comment by vitaly-safonov** [comment]
@elisafern12 Your metabox only displayed in a page with id 925
When you get post meta get_the_ID put current page or post id but your fields exist only in 925 page.
