### ISSUE TITLE
'undefined constant' error

### ISSUE THREAD

**Issue by squigglybob** [WebDevStudios/cmb2-attached-posts#22]
Hi,
I think this custom field code is great.
I have previously used it by dropping it into the cmb2 library files and it has worked fine that way.

I'm trying a new way now by dropping the files into the mu-plugins directory as suggested elsewhere.
CMB2 is installed as a WP plugin (I have removed the necessary lines of code because of this).
I was just checking the example-field-setup.php file worked fine, but unfortunately I get this error on the page where the meta box is partially appearing (due to the scripts and css not getting enqueued)

Notice: Use of undefined constant CMB2_ATTACHED_POSTS_FIELD_DIR - assumed 'CMB2_ATTACHED_POSTS_FIELD_DIR' in /home/redcom/public_html/stsaviours/wp-content/mu-plugins/init.php on line 220

The constant was obviously defined in the cmb2-attached-posts-field.php file where the init.php file was required as otherwise it wouldn't have been able to include it.

Any ideas what's going wrong?

Thanks,
Nath

**Comment by jtsternberg** [comment]
Can you provide the code you're using to include and the folder structure you're using?

**Comment by squigglybob** [comment]
sure.

wp-content
--themes
--plugins
----cmb2
--mu-plugins
----css
----js
----cmb2-attached-posts-field.php
----init.php
----etc. (all of the other cmb2-attached-post files)

I just dumped all of the cmb2-attached-post files into the mu-plugins folder.
I've not written any other code to include the cmb2-attached-post stuff in. I guessed wp would do the work for that, which it seems to be doing except for this issue.

And then the example-field-setup.php just worked automatically. Here's a screenshot.

![screenshot](https://cloud.githubusercontent.com/assets/9816214/14078689/c6ab5508-f4ef-11e5-8c69-e247770214d5.png)

**Comment by jtsternberg** [comment]
yah, you can't dump the contents of the lib in mu-plugins. You have to put the whole folder in mu-plugins in-tact, and add a mu-file which calls cmb2-attached-posts-field.php. Like this: https://gist.github.com/jtsternberg/1ec0f51e812b194ab87b

**Comment by squigglybob** [comment]
cool, thanks.
i've put it in a subdirectory in mu-plugins, and realised that the require_once line you had in your gist, is also in the top of the example_field_setup.php file, so I left that in there, and then tried a require_once( path-to-example-field-setup.php-file ) in my functions.php file, and now it works perfectly.

Thanks :)
