### ISSUE TITLE
Installation / Usage example for theme which bootstraps CMB2

### ISSUE THREAD

**Issue by monecchi** [WebDevStudios/cmb2-attached-posts#23]
Hello. Thanks for the CMB2 Attached Posts, I'm giving it a try right now.

My theme comes bundled with a plugin which requires CMB2 init.php file. If I'm not wrong this method is called bootstrap, so the issue is CMB2 is initiated through another required plugin.

So far I'm able to install some CMB2 add-ons as any other WordPress plugin while using those along with my theme's CMB2 set up, but I'm not sure about CMB2 Attached Posts installation instructions as long as it reads **_"If you're using CMB2 installed as a plugin, remove lines 6-9 of the example."**_

So the issue is if I don't use CMB2 as a plugin, where I'm supposed to place CMB2 Attached Posts files? Also, how and in which file would I require it?

Thanks in advance.

**Comment by jtsternberg** [comment]
The point is that you don't need to "include" CMB2 (like in the [example file](https://github.com/WebDevStudios/cmb2-attached-posts/blob/master/example-field-setup.php#L9)), unless you have not already figured that part out. If your theme has CMB2 bundled, you're good. If you install cmb2-attached-posts as a plugin, then you don't need [this line](https://github.com/WebDevStudios/cmb2-attached-posts/blob/master/example-field-setup.php#L10) either.

**Comment by monecchi** [comment]
@jtsternberg Thanks for the input. I wanted the **CMB2 Attached Posts** to be more of a dependency rather than have it installed as a plugin, so I just looked for the file where my theme's plugin requires CMB2 and then required CMB2 Attached Posts as per the [example file](https://github.com/WebDevStudios/cmb2-attached-posts/blob/master/example-field-setup.php#L10)'s reference. It works as expected. Thanks!.
