### ISSUE TITLE
Load max 20 post and search more by Ajax

### ISSUE THREAD

**Issue by dankocrama980** [WebDevStudios/cmb2-attached-posts#26]
Hello,

I would like to know if there is a way to load lets say 20 post and if we use the search that them it gets more posts by ajax, that are matching the search. because we have more the 20.000 post so we can't load the page.

Hope you can help us out

**Comment by mckernanin** [comment]
You might want to try this plugin: https://github.com/WebDevStudios/CMB2-Post-Search-field

**Comment by dankocrama980** [comment]
Thanks for the reply 👍 i already use this plugin but find the usability less.

**Comment by mralessio** [comment]
I would agree with @dankocrama980. Two thumbs up if search/autocomplete functionality would be in this plugin. Also tried Post Search Field, but it shows just IDs in the field, which is not convinient for users or editors, so after selecting some posts you can't remember the actual posts' name and reselect them, and no thumbnails. I'd say it's quite specific. 

cmb2-attached-posts is much more in line for the goal of connecting any related items, as it works in very visually friendly way. Once you return to the post you see what are related already and can add/remove quickly. If it had the search/autocomplete functionality it would be really a great and complete solution. Much as like as ACF has for this kind of things.

**Comment by jtsternberg** [comment]
I would also agree, two 👍👍 for this feature. I doubt I'll be able to get to it soon, but would be happy to take a look at a PR.

**Comment by luxdeluks** [comment]
Have you perhaps considered using a select element and then attaching for example select2 ?

In fact I'll try and modify the code these days if I get the time since the current selection process isn't really 'user-friendly' in that you can't just click the whole element.

**Comment by jtsternberg** [comment]
Closing this as we now have a search feature to search for posts not in the list.
