### ISSUE TITLE
Usage with CMB2 repo version

### ISSUE THREAD

**Issue by lmartins** [WebDevStudios/cmb2-attached-posts#5]
I would prefer to keep using the Wordpress repository version of CMB2 with cmb2-attached-posts, is that possible?

**Comment by tw2113** [comment]
CMB2 should be able to be used either as a standalone lib still, or as the plugin-ready version. Hope that helps.

**Comment by jtsternberg** [comment]
The example assumes you have both CMB2 and this extension in your mu-plugins directory, but If you're using CMB2 installed as a plugin, remove [line 6 of the example](https://github.com/WebDevStudios/cmb2-attached-posts/blob/master/example-field-setup.php#L6).

**Comment by lmartins** [comment]
Brilliant, thanks.
